version: '3.3'
services:
  nginx:
    image: vjirovsky/azure-nette-nginx:latest

    restart: always

    ports:
      - 8000:80

    volumes:
      #following line is used for debugging at local computer
      #- ./var_www:/var/www/html
      #following lines are used for live app on Azure Web App, in case of WEBSITES_ENABLE_APP_SERVICE_STORAGE = true
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot:/var/www/html
      - ${WEBAPP_STORAGE_HOME}/LogFiles:/var/log
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "5m"

    depends_on:
      - fpm
  fpm:
    image: vjirovsky/azure-nette-fpm:latest

    restart: always

    ports:
      - 9000:9000

    volumes:
      #following line is used for debugging at local computer
      #- ./var_www:/var/www/html
      #following lines are used for live app on Azure Web App, in case of WEBSITES_ENABLE_APP_SERVICE_STORAGE = true
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot:/var/www/html
      - ${WEBAPP_STORAGE_HOME}/LogFiles:/var/log
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "5m"

